peliculas = [
  {'id': 1, 'titulo': 'Indiana Jones', 'genero': 'Acción'},
  {'id': 2, 'titulo': 'Star Wars', 'genero': 'Acción'},
  {'id': 3, 'titulo': 'Interstellar', 'genero': 'Ciencia ficción'},
  {'id': 4, 'titulo': 'Jurassic Park', 'genero': 'Aventura'},
  {'id': 5, 'titulo': 'The Avengers', 'genero': 'Acción'},
  {'id': 6, 'titulo': 'Back to the Future', 'genero': 'Ciencia ficción'},
  {'id': 7, 'titulo': 'The Lord of the Rings', 'genero': 'Fantasía'},
  {'id': 8, 'titulo': 'The Dark Knight', 'genero': 'Acción'},
  {'id': 9, 'titulo': 'Inception', 'genero': 'Ciencia ficción'},
  {'id': 10, 'titulo': 'The Shawshank Redemption', 'genero': 'Drama'},
  {'id': 11, 'titulo': 'Pulp Fiction', 'genero': 'Crimen'},
  {'id': 12, 'titulo': 'Fight Club', 'genero': 'Drama'},
  {'id': 13, 'titulo': 'Avatar', 'genero': 'Acción'},
  {'id': 14, 'titulo': 'The Matrix', 'genero': 'Ciencia ficción'},
  {'id': 15, 'titulo': 'Harry Potter', 'genero': 'Fantasía'},
  {'id': 16, 'titulo': 'The Godfather', 'genero': 'Crimen'},
  {'id': 17, 'titulo': 'Titanic', 'genero': 'Romance'},
  {'id': 18, 'titulo': 'Forrest Gump', 'genero': 'Drama'},
  {'id': 19, 'titulo': 'Gladiator', 'genero': 'Acción'},
  {'id': 20, 'titulo': 'The Lion King', 'genero': 'Animación'},
  {'id': 21, 'titulo': 'The Terminator', 'genero': 'Ciencia ficción'},
  {'id': 22, 'titulo': 'The Shawshank Redemption', 'genero': 'Drama'},
  {'id': 23, 'titulo': 'The Silence of the Lambs', 'genero': 'Suspenso'},
  {'id': 24, 'titulo': 'The Sixth Sense', 'genero': 'Terror'},
  {'id': 25, 'titulo': 'Inglourious Basterds', 'genero': 'Acción'},
  {'id': 26, 'titulo': 'The Green Mile', 'genero': 'Drama'},
  {'id': 27, 'titulo': 'The Departed', 'genero': 'Crimen'},
  {'id': 28, 'titulo': 'The Shawshank Redemption', 'genero': 'Drama'},
  {'id': 29, 'titulo': 'The Prestige', 'genero': 'Drama'},
  {'id': 30, 'titulo': 'Se7en', 'genero': 'Crimen'},
  {'id': 31, 'titulo': 'Inferno', 'genero': 'Misterio'},
  {'id': 32, 'titulo': 'The Martian', 'genero': 'Ciencia ficción'},
  {'id': 33, 'titulo': 'The Grand Budapest Hotel', 'genero': 'Comedia'},
  {'id': 34, 'titulo': 'The Revenant', 'genero': 'Aventura'},
  {'id': 35, 'titulo': 'La La Land', 'genero': 'Musical'},
  {'id': 36, 'titulo': 'The Social Network', 'genero': 'Drama'},
  {'id': 37, 'titulo': 'The Notebook', 'genero': 'Romance'},
  {'id': 38, 'titulo': 'Gone Girl', 'genero': 'Misterio'},
  {'id': 39, 'titulo': 'The Hangover', 'genero': 'Comedia'},
  {'id': 40, 'titulo': 'Mad Max: Fury Road', 'genero': 'Acción'},
  {'id': 41, 'titulo': 'The Wolf of Wall Street', 'genero': 'Crimen'},
  {'id': 42, 'titulo': 'The Curious Case of Benjamin Button', 'genero': 'Fantasía'},
  {'id': 43, 'titulo': 'Inception', 'genero': 'Ciencia ficción'},
  {'id': 44, 'titulo': 'The Princess Bride', 'genero': 'Aventura'},
  {'id': 45, 'titulo': 'The Great Gatsby', 'genero': 'Drama'},
  {'id': 46, 'titulo': 'Finding Nemo', 'genero': 'Animación'},
  {'id': 47, 'titulo': 'The Breakfast Club', 'genero': 'Drama'},
  {'id': 48, 'titulo': 'The Truman Show', 'genero': 'Drama'},
  {'id': 49, 'titulo': 'Shutter Island', 'genero': 'Misterio'},
  {'id': 50, 'titulo': 'The Usual Suspects', 'genero': 'Crimen'}
]